### ISSUE TITLE
is six missing as a dependancy listed in the setup? easy_install http://github.com/ahlmss/pkglib/tarball/master#egg=pkglib fails...

### ISSUE THREAD

**Issue by oisinmulvihill** [man-group/pkglib#23]
```
easy_install http://github.com/ahlmss/pkglib/tarball/master#egg=pkglib
Downloading http://github.com/ahlmss/pkglib/tarball/master#egg=pkglib
Processing master
Writing /var/folders/qx/_80tny9n3hv7zftq4pmf96cc0000gn/T/easy_install-zac0SG/ahlmss-pkglib-bf190b0/setup.cfg
Running ahlmss-pkglib-bf190b0/setup.py -q bdist_egg --dist-dir /var/folders/qx/_80tny9n3hv7zftq4pmf96cc0000gn/T/easy_install-zac0SG/ahlmss-pkglib-bf190b0/egg-dist-tmp-qo6gvc
Traceback (most recent call last):
  File "/Users/oisin/virtualenvs/t2/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==0.9.8', 'console_scripts', 'easy_install')()
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1992, in main
    with_ei_usage(lambda:
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1979, in with_ei_usage
    return f()
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1996, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 599, in easy_install
    return self.install_item(None, download, tmpdir, deps, True)
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
    run_setup(setup_script, args)
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/sandbox.py", line 120, in run
    return func()
  File "/Users/oisin/virtualenvs/t2/lib/python2.7/site-packages/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 3, in <module>
  File "pkglib/pkglib/__init__.py", line 4, in <module>
  File "pkglib/pkglib/config.py", line 15, in <module>
  File "pkglib/pkglib/util.py", line 5, in <module>
ImportError: No module named six
```

**Comment by eeaston** [comment]
Master will be rolled back, it was an accidental merge that caused this.  We're working to merge in 12m of work from AHL into the ahl2012 branch over the next few days - hold tight!

**Comment by Wilfred** [comment]
This should now be fixed by https://github.com/ahlmss/pkglib/pull/26 .
