### ISSUE TITLE
pkglib requires distribute

### ISSUE THREAD

**Issue by Wilfred** [man-group/pkglib#31]
Install fails if I use setuptools.

```
$ virtualenv ~/.py_envs/pkglib -p python2
Already using interpreter /usr/bin/python2
New python executable in /home/wilfred/.py_envs/pkglib/bin/python2
Also creating executable in /home/wilfred/.py_envs/pkglib/bin/python
Installing setuptools............done.
Installing pip...............done.
$ . ~/.py_envs/pkglib/bin/activate
(pkglib)$ python setup.py install
In directory pkglib-util: Running '/home/wilfred/.py_envs/pkglib/bin/python setup.py install'
running install
running bdist_egg
running egg_info
creating pkglib_util.egg-info
writing pkglib_util.egg-info/PKG-INFO
writing top-level names to pkglib_util.egg-info/top_level.txt
writing dependency_links to pkglib_util.egg-info/dependency_links.txt
writing manifest file 'pkglib_util.egg-info/SOURCES.txt'
reading manifest file 'pkglib_util.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cpp' under directory 'tests'
warning: no files found matching '*.hpp' under directory 'tests'
warning: no files found matching '*.c' under directory 'tests'
warning: no files found matching '*.h' under directory 'tests'
warning: no files found matching '*.pyx' under directory 'tests'
writing manifest file 'pkglib_util.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pkglib_util
copying pkglib_util/__init__.py -> build/lib/pkglib_util
copying pkglib_util/cmdline.py -> build/lib/pkglib_util
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pkglib_util
copying build/lib/pkglib_util/__init__.py -> build/bdist.linux-x86_64/egg/pkglib_util
copying build/lib/pkglib_util/cmdline.py -> build/bdist.linux-x86_64/egg/pkglib_util
byte-compiling build/bdist.linux-x86_64/egg/pkglib_util/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_util/cmdline.py to cmdline.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_util.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_util.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_util.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_util.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pkglib_util-0.10.5.dev1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pkglib_util-0.10.5.dev1-py2.7.egg
Copying pkglib_util-0.10.5.dev1-py2.7.egg to /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages
Adding pkglib-util 0.10.5.dev1 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/pkglib_util-0.10.5.dev1-py2.7.egg
Processing dependencies for pkglib-util==0.10.5.dev1
Finished processing dependencies for pkglib-util==0.10.5.dev1
In directory pkglib-testing: Running '/home/wilfred/.py_envs/pkglib/bin/python setup.py install'
running install
running bdist_egg
running egg_info
creating pkglib_testing.egg-info
writing requirements to pkglib_testing.egg-info/requires.txt
writing pkglib_testing.egg-info/PKG-INFO
writing top-level names to pkglib_testing.egg-info/top_level.txt
writing dependency_links to pkglib_testing.egg-info/dependency_links.txt
writing manifest file 'pkglib_testing.egg-info/SOURCES.txt'
reading manifest file 'pkglib_testing.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cpp' under directory 'tests'
warning: no files found matching '*.hpp' under directory 'tests'
warning: no files found matching '*.c' under directory 'tests'
warning: no files found matching '*.h' under directory 'tests'
warning: no files found matching '*.pyx' under directory 'tests'
warning: no files found matching '*.cpp' under directory 'pkglib_testing'
warning: no files found matching '*.hpp' under directory 'pkglib_testing'
warning: no files found matching '*.c' under directory 'pkglib_testing'
warning: no files found matching '*.h' under directory 'pkglib_testing'
warning: no files found matching '*.pyx' under directory 'pkglib_testing'
writing manifest file 'pkglib_testing.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pkglib_testing
copying pkglib_testing/server.py -> build/lib/pkglib_testing
copying pkglib_testing/config.py -> build/lib/pkglib_testing
copying pkglib_testing/process.py -> build/lib/pkglib_testing
copying pkglib_testing/util.py -> build/lib/pkglib_testing
copying pkglib_testing/jasmine_results_page.py -> build/lib/pkglib_testing
copying pkglib_testing/listener_client.py -> build/lib/pkglib_testing
copying pkglib_testing/xvfb_server.py -> build/lib/pkglib_testing
copying pkglib_testing/redis_server.py -> build/lib/pkglib_testing
copying pkglib_testing/page_objects.py -> build/lib/pkglib_testing
copying pkglib_testing/__init__.py -> build/lib/pkglib_testing
copying pkglib_testing/pypi.py -> build/lib/pkglib_testing
copying pkglib_testing/listener.py -> build/lib/pkglib_testing
copying pkglib_testing/mongo_server.py -> build/lib/pkglib_testing
copying pkglib_testing/httpd_proxy_server.py -> build/lib/pkglib_testing
copying pkglib_testing/jenkins_server.py -> build/lib/pkglib_testing
copying pkglib_testing/webdriver.py -> build/lib/pkglib_testing
copying pkglib_testing/cmdline.py -> build/lib/pkglib_testing
copying pkglib_testing/pyramid_server.py -> build/lib/pkglib_testing
creating build/lib/pkglib_testing/mocking
copying pkglib_testing/mocking/oracle.py -> build/lib/pkglib_testing/mocking
copying pkglib_testing/mocking/subprocess.py -> build/lib/pkglib_testing/mocking
copying pkglib_testing/mocking/__init__.py -> build/lib/pkglib_testing/mocking
copying pkglib_testing/mocking/package.py -> build/lib/pkglib_testing/mocking
copying pkglib_testing/mocking/misc.py -> build/lib/pkglib_testing/mocking
creating build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/coverage.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/parametrize_ids.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/util.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/profile.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/redis_server_session.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/redis_server.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/q_application.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/__init__.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/simple_http_server.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/mongo_server.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/jenkins_server.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/webdriver.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/mongo_server_class.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/pyramid_server.py -> build/lib/pkglib_testing/pytest
copying pkglib_testing/pytest/mongo_server_session.py -> build/lib/pkglib_testing/pytest
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/server.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/config.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/process.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/util.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/jasmine_results_page.py -> build/bdist.linux-x86_64/egg/pkglib_testing
creating build/bdist.linux-x86_64/egg/pkglib_testing/mocking
copying build/lib/pkglib_testing/mocking/oracle.py -> build/bdist.linux-x86_64/egg/pkglib_testing/mocking
copying build/lib/pkglib_testing/mocking/subprocess.py -> build/bdist.linux-x86_64/egg/pkglib_testing/mocking
copying build/lib/pkglib_testing/mocking/__init__.py -> build/bdist.linux-x86_64/egg/pkglib_testing/mocking
copying build/lib/pkglib_testing/mocking/package.py -> build/bdist.linux-x86_64/egg/pkglib_testing/mocking
copying build/lib/pkglib_testing/mocking/misc.py -> build/bdist.linux-x86_64/egg/pkglib_testing/mocking
copying build/lib/pkglib_testing/listener_client.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/xvfb_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/redis_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing
creating build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/coverage.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/parametrize_ids.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/util.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/profile.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/redis_server_session.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/redis_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/q_application.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/__init__.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/simple_http_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/mongo_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/jenkins_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/webdriver.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/mongo_server_class.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/pyramid_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/pytest/mongo_server_session.py -> build/bdist.linux-x86_64/egg/pkglib_testing/pytest
copying build/lib/pkglib_testing/page_objects.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/__init__.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/pypi.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/listener.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/mongo_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/httpd_proxy_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/jenkins_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/webdriver.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/cmdline.py -> build/bdist.linux-x86_64/egg/pkglib_testing
copying build/lib/pkglib_testing/pyramid_server.py -> build/bdist.linux-x86_64/egg/pkglib_testing
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/server.py to server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/process.py to process.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/util.py to util.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/jasmine_results_page.py to jasmine_results_page.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/mocking/oracle.py to oracle.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/mocking/subprocess.py to subprocess.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/mocking/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/mocking/package.py to package.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/mocking/misc.py to misc.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/listener_client.py to listener_client.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/xvfb_server.py to xvfb_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/redis_server.py to redis_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/coverage.py to coverage.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/parametrize_ids.py to parametrize_ids.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/util.py to util.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/profile.py to profile.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/redis_server_session.py to redis_server_session.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/redis_server.py to redis_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/q_application.py to q_application.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/simple_http_server.py to simple_http_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/mongo_server.py to mongo_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/jenkins_server.py to jenkins_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/webdriver.py to webdriver.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/mongo_server_class.py to mongo_server_class.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/pyramid_server.py to pyramid_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pytest/mongo_server_session.py to mongo_server_session.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/page_objects.py to page_objects.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pypi.py to pypi.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/listener.py to listener.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/mongo_server.py to mongo_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/httpd_proxy_server.py to httpd_proxy_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/jenkins_server.py to jenkins_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/webdriver.py to webdriver.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/cmdline.py to cmdline.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkglib_testing/pyramid_server.py to pyramid_server.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_testing.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_testing.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_testing.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_testing.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pkglib_testing.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pkglib_testing.util: module references __file__
pkglib_testing.util: module MAY be using inspect.getsource
creating dist
creating 'dist/pkglib_testing-0.10.5.dev1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pkglib_testing-0.10.5.dev1-py2.7.egg
creating /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/pkglib_testing-0.10.5.dev1-py2.7.egg
Extracting pkglib_testing-0.10.5.dev1-py2.7.egg to /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages
Adding pkglib-testing 0.10.5.dev1 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/pkglib_testing-0.10.5.dev1-py2.7.egg
Processing dependencies for pkglib-testing==0.10.5.dev1
Searching for python-jenkins
Reading http://pypi.python.org/simple/python-jenkins/
Reading http://launchpad.net/python-jenkins
Best match: python-jenkins 0.2.1
Downloading https://launchpad.net/python-jenkins/0.2/0.2.1/+download/python-jenkins-0.2.1.tar.gz
Processing python-jenkins-0.2.1.tar.gz
Running python-jenkins-0.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ZnI0gt/python-jenkins-0.2.1/egg-dist-tmp-yRcCZr
zip_safe flag not set; analyzing archive contents...
Adding python-jenkins 0.2.1 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/python_jenkins-0.2.1-py2.7.egg
Searching for path.py
Reading http://pypi.python.org/simple/path.py/
Best match: path.py 5.1
Downloading https://pypi.python.org/packages/source/p/path.py/path.py-5.1.zip#md5=67c0e1b8c1b1b889ea77aef5224ccc29
Processing path.py-5.1.zip
Running path.py-5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-K9USUC/path.py-5.1/egg-dist-tmp-0EVPBb
zip_safe flag not set; analyzing archive contents...
Adding path.py 5.1 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/path.py-5.1-py2.7.egg
Searching for SQLAlchemy
Reading http://pypi.python.org/simple/SQLAlchemy/
Best match: SQLAlchemy 0.9.3
Downloading https://pypi.python.org/packages/source/S/SQLAlchemy/SQLAlchemy-0.9.3.tar.gz#md5=a27989b9d4b3f14ea0b1600aa45559c4
Processing SQLAlchemy-0.9.3.tar.gz
Running SQLAlchemy-0.9.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nkCwrN/SQLAlchemy-0.9.3/egg-dist-tmp-OoutLl
warning: no files found matching '*.jpg' under directory 'doc'
warning: no files found matching 'distribute_setup.py'
warning: no files found matching 'sa2to3.py'
warning: no files found matching 'ez_setup.py'
no previously-included directories found matching 'doc/build/output'
zip_safe flag not set; analyzing archive contents...
Adding SQLAlchemy 0.9.3 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/SQLAlchemy-0.9.3-py2.7-linux-x86_64.egg
Searching for pymongo
Reading http://pypi.python.org/simple/pymongo/
Best match: pymongo 2.6.3
Downloading https://pypi.python.org/packages/source/p/pymongo/pymongo-2.6.3.tar.gz#md5=da4a7d6ee47fe30b3978b8805d266167
Processing pymongo-2.6.3.tar.gz
Running pymongo-2.6.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pSWyZ_/pymongo-2.6.3/egg-dist-tmp-5W2Cvj
zip_safe flag not set; analyzing archive contents...
Adding pymongo 2.6.3 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/pymongo-2.6.3-py2.7-linux-x86_64.egg
Searching for selenium
Reading http://pypi.python.org/simple/selenium/
Best match: selenium 2.40.0
Downloading https://pypi.python.org/packages/source/s/selenium/selenium-2.40.0.tar.gz#md5=25a990c1b253ef452eec878cd63c894e
Processing selenium-2.40.0.tar.gz
Running selenium-2.40.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lPAMNg/selenium-2.40.0/egg-dist-tmp-K2Bmw0
Adding selenium 2.40.0 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/selenium-2.40.0-py2.7.egg
Searching for redis
Reading http://pypi.python.org/simple/redis/
Best match: redis 2.9.1
Downloading https://pypi.python.org/packages/source/r/redis/redis-2.9.1.tar.gz#md5=1da8ff78be75d7acf5d4684e77fc3606
Processing redis-2.9.1.tar.gz
Running redis-2.9.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wu0hEy/redis-2.9.1/egg-dist-tmp-bQUC4u
warning: no previously-included files found matching '__pycache__'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
zip_safe flag not set; analyzing archive contents...
Adding redis 2.9.1 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/redis-2.9.1-py2.7.egg
Searching for execnet
Reading http://pypi.python.org/simple/execnet/
Best match: execnet 1.2.0
Downloading https://pypi.python.org/packages/source/e/execnet/execnet-1.2.0.tar.gz#md5=1886d12726b912fc2fd05dfccd7e6432
Processing execnet-1.2.0.tar.gz
Running execnet-1.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-CyPLww/execnet-1.2.0/egg-dist-tmp-WQKXay
warning: no files found matching 'conftest.py'
zip_safe flag not set; analyzing archive contents...
execnet.apipkg: module references __file__
execnet.apipkg: module references __path__
execnet.gateway_bootstrap: module references __file__
execnet.gateway_bootstrap: module MAY be using inspect.getsource
execnet.gateway: module references __file__
execnet.gateway: module MAY be using inspect.getsource
execnet.gateway: module MAY be using inspect.getsourcefile
execnet.script.socketserverservice: module references __file__
Adding execnet 1.2.0 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/execnet-1.2.0-py2.7.egg
Searching for contextlib2
Reading http://pypi.python.org/simple/contextlib2/
Best match: contextlib2 0.4.0
Downloading https://pypi.python.org/packages/source/c/contextlib2/contextlib2-0.4.0.tar.gz#md5=ea687207db25f65552061db4a2c6727d
Processing contextlib2-0.4.0.tar.gz
Running contextlib2-0.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-R50FPS/contextlib2-0.4.0/egg-dist-tmp-coYlJM
zip_safe flag not set; analyzing archive contents...
Adding contextlib2 0.4.0 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/contextlib2-0.4.0-py2.7.egg
Searching for mock
Reading http://pypi.python.org/simple/mock/
Best match: mock 1.0.1
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.0.1.zip#md5=869f08d003c289a97c1a6610faf5e913
Processing mock-1.0.1.zip
Running mock-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-igbkeg/mock-1.0.1/egg-dist-tmp-6zXSS8
warning: no files found matching '*.png' under directory 'docs'
warning: no files found matching '*.css' under directory 'docs'
warning: no files found matching '*.html' under directory 'docs'
warning: no files found matching '*.js' under directory 'docs'
zip_safe flag not set; analyzing archive contents...
Adding mock 1.0.1 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/mock-1.0.1-py2.7.egg
Searching for pytest-cov
Reading http://pypi.python.org/simple/pytest-cov/
Best match: pytest-cov 1.6
Downloading https://pypi.python.org/packages/source/p/pytest-cov/pytest-cov-1.6.tar.gz#md5=6da54d74bde9d200de45068ba2ea637a
Processing pytest-cov-1.6.tar.gz
Running pytest-cov-1.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6kRrcu/pytest-cov-1.6/egg-dist-tmp-Wd8TEc
Adding pytest-cov 1.6 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/pytest_cov-1.6-py2.7.egg
Searching for pytest
Reading http://pypi.python.org/simple/pytest/
Best match: pytest 2.5.2
Downloading https://pypi.python.org/packages/source/p/pytest/pytest-2.5.2.tar.gz#md5=8ea3d1939e81514ccba9ba0e9566b5be
Processing pytest-2.5.2.tar.gz
Running pytest-2.5.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-KoP0fL/pytest-2.5.2/egg-dist-tmp-1uYTiN
Adding pytest 2.5.2 to easy-install.pth file
Installing py.test script to /home/wilfred/.py_envs/pkglib/bin
Installing py.test-2.7 script to /home/wilfred/.py_envs/pkglib/bin

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/pytest-2.5.2-py2.7.egg
Searching for cov-core>=1.6
Reading http://pypi.python.org/simple/cov-core/
Best match: cov-core 1.7
Downloading https://pypi.python.org/packages/source/c/cov-core/cov-core-1.7.tar.gz#md5=59c1e22e636633e10120beacbf45b28c
Processing cov-core-1.7.tar.gz
Running cov-core-1.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7DCu5j/cov-core-1.7/egg-dist-tmp-uONlOM
Adding cov-core 1.7 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/cov_core-1.7-py2.7.egg
Searching for py>=1.4.20
Reading http://pypi.python.org/simple/py/
Best match: py 1.4.20
Downloading https://pypi.python.org/packages/source/p/py/py-1.4.20.tar.gz#md5=5f1708be5482f3ff6711dfd6cafd45e0
Processing py-1.4.20.tar.gz
Running py-1.4.20/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2A3QaT/py-1.4.20/egg-dist-tmp-HDHm4N
Adding py 1.4.20 to easy-install.pth file

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/py-1.4.20-py2.7.egg
Searching for coverage>=3.4
Reading http://pypi.python.org/simple/coverage/
Best match: coverage 3.7.1
Downloading https://pypi.python.org/packages/source/c/coverage/coverage-3.7.1.tar.gz#md5=c47b36ceb17eaff3ecfab3bcd347d0df
Processing coverage-3.7.1.tar.gz
Running coverage-3.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Rg9hTw/coverage-3.7.1/egg-dist-tmp-lpncQ3
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Adding coverage 3.7.1 to easy-install.pth file
Installing coverage2 script to /home/wilfred/.py_envs/pkglib/bin
Installing coverage-2.7 script to /home/wilfred/.py_envs/pkglib/bin
Installing coverage script to /home/wilfred/.py_envs/pkglib/bin

Installed /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/coverage-3.7.1-py2.7-linux-x86_64.egg
Searching for pkglib-util==0.10.5.dev1
Best match: pkglib-util 0.10.5.dev1
Processing pkglib_util-0.10.5.dev1-py2.7.egg
pkglib-util 0.10.5.dev1 is already the active version in easy-install.pth

Using /home/wilfred/.py_envs/pkglib/lib/python2.7/site-packages/pkglib_util-0.10.5.dev1-py2.7.egg
Finished processing dependencies for pkglib-testing==0.10.5.dev1
In directory pkglib: Running '/home/wilfred/.py_envs/pkglib/bin/python setup.py install'
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from pkglib.setuptools.command import easy_install
  File "/home/wilfred/work/ahl/pkglib/pkglib/pkglib/setuptools/__init__.py", line 23, in <module>
    from ._setup import setup
  File "/home/wilfred/work/ahl/pkglib/pkglib/pkglib/setuptools/_setup.py", line 10, in <module>
    from pkglib.setuptools.command import (develop, test, jenkins_, egg_info, easy_install,
  File "/home/wilfred/work/ahl/pkglib/pkglib/pkglib/setuptools/command/develop.py", line 12, in <module>
    from .easy_install import easy_install
  File "/home/wilfred/work/ahl/pkglib/pkglib/pkglib/setuptools/command/easy_install.py", line 9, in <module>
    from setuptools.command.easy_install import (easy_install as _easy_install,
ImportError: cannot import name is_64bit
No handlers could be found for logger "pkglib_util.cmdline"
Command failed with exit code 1
```

It works as expected if I pass `--distribute` to virtualenv.

We should at least provide installation instructions, and we ought to support setuptools too. I'm puzzled as to why Travis doesn't see this issue though.

**Comment by eeaston** [comment]
That is odd, I've been using setuptools 2.2 for my own testing and it seems
OK so far. I'll have a bit of a dig.

**Comment by Wilfred** [comment]
I was on setuptools 0.6c11, FWIW. It's old, but it's still the default on some linux distros. Since it's possible to update setuptools once you're in a virtualenv, documentation would probably suffice.
